<?php

 $_CONFIG = array (
  'appname' => 'File Manager',
  'skin' => 'blank.css',
  'logo' => 'logo.png',
  'show_head' => true,
  'lang' => 'en',
  'show_langmenu' => true,
  'thumbnails' => true,
  'thumbnails_width' => 600,
  'thumbnails_height' => 800,
  'inline_thumbs' => false,
  'show_path' => true,
  'time_format' => 'd/m/Y - H:i',
  'require_login' => true,
  'starting_dir' => './uploads/',
  'preloader' => 'XMLHttpRequest',
  'salt' => '',
  'upload_enable' => true,
  'newdir_enable' => true,
  'delete_enable' => true,
  'rename_enable' => true,
  'hidden_files' => 
  array (
    0 => 'doc-thumb.php',
    1 => 'index.php',
    2 => 'index.php~',
    3 => '.htaccess',
    4 => '.htpasswd',
    5 => '.ftpquota',
  ),
  'hidden_dirs' => 
  array (
    0 => 'doc-admin',
  ),
  'upload_allow_type' => 
  array (
  ),
  'upload_reject_extension' => 
  array (
    0 => 'php',
    1 => 'html',
    2 => 'htm',
  ),
  'upload_email' => false,
  'log_file' => false,
  'basedir' => '',
  'session_name' => '',
  'show_pagination' => true,
  'show_pagination_num' => true,
  'show_search' => true,
  'sendfiles_enable' => true,
  'lifetime' => 1,
  'smtp_enable' => false,
  'smtp_auth' => false,
  'email_from' => '',
  'smtp_server' => '',
  'port' => '',
  'secure_conn' => 'none',
  'email_login' => '',
  'email_pass' => '',
  'progress_color' => '',
  'show_usermenu' => true,
  'default_timezone' => 'UTC',
  'description' => '',
  'show_pagination_folders' => false,
  'show_captcha' => false,
  'show_captcha_reset' => true,
  'filedefnum' => 10,
  'filedeforder' => 'date',
  'folderdefnum' => 10,
  'folderdeforder' => 'alpha',
  'playmusic' => true,
  'txt_direction' => 'LTR',
  'max_zip_files' => 100,
  'max_zip_filesize' => 100,
  'show_percentage' => false,
  'notify_login' => false,
  'notify_upload' => false,
  'notify_download' => false,
  'notify_newfolder' => false,
  'align_logo' => 'left',
  'single_progress' => false,
  'enable_prettylinks' => false,
  'secure_sharing' => false,
  'show_pagination_num_folder' => false,
  'script_url' => '',
);
